export const dummyData = {
  users: [
    {
      userId: 1,
      username: 'john_doe',
      email: 'john@example.com',
      transactions: [
        {
          id: 1,
          title: 'Grocery Shopping',
          amount: 200,
          date: '2024-08-03',
          category: 'Food',
          type: 'expense',
          icon: 'fa-solid fa-utensils',
        },
        {
          id: 2,
          title: 'Freelance Project',
          amount: 1200,
          date: '2024-08-05',
          category: 'Work',
          type: 'income',
          icon: 'fa-solid fa-briefcase',
        },
        {
          id: 3,
          title: 'Electricity Bill',
          amount: 100,
          date: '2024-08-10',
          category: 'Utilities',
          type: 'expense',
          icon: 'fa-solid fa-plug',
        },
        {
          id: 4,
          title: 'Rent',
          amount: 1200,
          date: '2024-09-01',
          category: 'Rent',
          type: 'expense',
          icon: 'fa-solid fa-house-chimney',
        },
        {
          id: 5,
          title: 'Salary',
          amount: 3000,
          date: '2024-09-01',
          category: 'Salary',
          type: 'income',
          icon: 'fa-solid fa-money-bill',
        },
        {
          id: 6,
          title: 'Bonus',
          amount: 8000,
          date: '2024-09-12',
          category: 'Salary',
          type: 'income',
          icon: 'fa-solid fa-money-bill',
        },
        {
          id: 7,
          title: 'Restaurant',
          amount: 150,
          date: '2024-09-12',
          category: 'Food',
          type: 'expense',
          icon: 'fa-solid fa-utensils',
        },
        {
          id: 8,
          title: 'Gym Membership',
          amount: 50,
          date: '2024-09-15',
          category: 'Health',
          type: 'expense',
          icon: 'fa-solid fa-kit-medical',
        },
        {
          id: 9,
          title: 'Vacation',
          amount: 1000,
          date: '2024-09-17',
          category: 'Leisure',
          type: 'expense',
          icon: 'fa-solid fa-umbrella-beach',
        },
        {
          id: 10,
          title: 'Lottery',
          amount: 11000,
          date: '2024-09-19',
          category: 'Other Income',
          type: 'income',
          icon: 'fa-solid fa-money-bill',
        },
        {
          id: 11,
          title: 'Online Course',
          amount: 300,
          date: '2024-09-03',
          category: 'Education',
          type: 'expense',
          icon: 'fa-solid fa-school',
        },
        {
          id: 12,
          title: 'Car Insurance',
          amount: 600,
          date: '2024-09-06',
          category: 'Insurance',
          type: 'expense',
          icon: 'fa-solid fa-user-shield',
        },
        {
          id: 13,
          title: 'Clothing Shopping',
          amount: 350,
          date: '2024-09-10',
          category: 'Clothing',
          type: 'expense',
          icon: 'fa-solid fa-shirt',
        },
        {
          id: 14,
          title: 'Freelance Project 2',
          amount: 2500,
          date: '2024-09-18',
          category: 'Freelance',
          type: 'income',
          icon: 'fa-solid fa-money-bill',
        },
      ],
      budgets: [
        {
          category: 'Food',
          period: 'monthly',
          limit: 500,
          currentSpending: 350,
          startDate: '2024-09-01',
          endDate: '2024-09-30',
        },
        {
          category: 'Utilities',
          period: 'monthly',
          limit: 200,
          currentSpending: 100,
          startDate: '2024-09-01',
          endDate: '2024-09-30',
        },
        {
          category: 'Rent',
          period: 'monthly',
          limit: 1200,
          currentSpending: 1200,
          startDate: '2024-09-01',
          endDate: '2024-09-30',
        },
      ],
      reminders: [
        {
          id: 1,
          title: 'Pay Rent',
          dueDate: '2024-09-01',
          notificationDate: '2024-08-30',
          recurring: true,
        },
        {
          id: 2,
          title: 'Electricity Bill',
          dueDate: '2024-09-10',
          notificationDate: '2024-09-08',
          recurring: true,
        },
      ],
    },
  ],
};
