export const dummyData = {
  users: [
    {
      userId: 1,
      username: 'john_doe',
      email: 'john@example.com',
      transactions: [
        {
          id: 1,
          title: 'Grocery Shopping',
          amount: 200,
          date: '2024-08-03',
          category: 'Food',
          type: 'expense',
        },
        {
          id: 2,
          title: 'Freelance Project',
          amount: 1200,
          date: '2024-08-05',
          category: 'Freelance',
          type: 'income',
        },
        {
          id: 3,
          title: 'Electricity Bill',
          amount: 100,
          date: '2024-08-10',
          category: 'Utilities',
          type: 'expense',
        },
        {
          id: 4,
          title: 'Rent',
          amount: 1200,
          date: '2024-09-01',
          category: 'Rent',
          type: 'expense',
        },
        {
          id: 5,
          title: 'Salary',
          amount: 3000,
          date: '2024-09-01',
          category: 'Salary',
          type: 'income',
        },
        {
          id: 6,
          title: 'Bonus',
          amount: 8000,
          date: '2024-09-12',
          category: 'Salary',
          type: 'income',
        },
        {
          id: 7,
          title: 'Restaurant',
          amount: 150,
          date: '2024-09-12',
          category: 'Food',
          type: 'expense',
        },
        {
          id: 8,
          title: 'Gym Membership',
          amount: 50,
          date: '2024-09-15',
          category: 'Health',
          type: 'expense',
        },
        {
          id: 9,
          title: 'Vacation',
          amount: 1000,
          date: '2024-09-17',
          category: 'Health',
          type: 'expense',
        },
        {
          id: 10,
          title: 'Lottery',
          amount: 11000,
          date: '2024-09-1',
          category: 'Health',
          type: 'income',
        },
      ],
      budgets: [
        {
          category: 'Food',
          period: 'monthly',
          limit: 500,
          currentSpending: 350,
          startDate: '2024-09-01',
          endDate: '2024-09-30',
        },
        {
          category: 'Utilities',
          period: 'monthly',
          limit: 200,
          currentSpending: 100,
          startDate: '2024-09-01',
          endDate: '2024-09-30',
        },
        {
          category: 'Rent',
          period: 'monthly',
          limit: 1200,
          currentSpending: 1200,
          startDate: '2024-09-01',
          endDate: '2024-09-30',
        },
      ],
      reminders: [
        {
          id: 1,
          title: 'Pay Rent',
          dueDate: '2024-09-01',
          notificationDate: '2024-08-30',
          recurring: true,
        },
        {
          id: 2,
          title: 'Electricity Bill',
          dueDate: '2024-09-10',
          notificationDate: '2024-09-08',
          recurring: true,
        },
      ],
    },
  ],
};
